'use strict';

const ERROR_CODES = {
  INVALID_PHONE: 'SMS_001',
  INVALID_TEMPLATE: 'SMS_002',
  PROVIDER_UNAVAILABLE: 'SMS_003',
  INSUFFICIENT_BALANCE: 'SMS_004',
  DUPLICATE_REFERENCE: 'SMS_005',
  RATE_LIMIT_EXCEEDED: 'SMS_006',
  BLACKLISTED_NUMBER: 'SMS_007',
  DLT_TEMPLATE_MISSING: 'SMS_008',
  OTP_EXPIRED: 'SMS_009',
  OTP_INVALID: 'SMS_010',
  OTP_MAX_ATTEMPTS: 'SMS_011',
  VALIDATION_ERROR: 'SMS_012',
  NOT_FOUND: 'SMS_013',
  UNAUTHORIZED: 'SMS_014',
  INTERNAL_ERROR: 'SMS_015',
};

// Errors that should NOT trigger a retry
const PERMANENT_ERROR_CODES = new Set([
  ERROR_CODES.INVALID_PHONE,
  ERROR_CODES.INSUFFICIENT_BALANCE,
  ERROR_CODES.BLACKLISTED_NUMBER,
  ERROR_CODES.DUPLICATE_REFERENCE,
  ERROR_CODES.DLT_TEMPLATE_MISSING,
]);

module.exports = { ERROR_CODES, PERMANENT_ERROR_CODES };
